let mapleader = " "
set number
set relativenumber
filetype plugin indent on
set expandtab
set shiftwidth=4
set signcolumn=yes
set softtabstop=4
set tabstop=4
set smartindent 
syntax on

call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-vinegar'
Plug 'sainnhe/everforest'
Plug 'junegunn/fzf', { 'do': { -> fzf#install()  }  }
Plug 'junegunn/fzf.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'jiangmiao/auto-pairs'
Plug 'vim-airline/vim-airline'
call plug#end()

if has('termguicolors')
    set termguicolors
endif

set background=dark

let g:everforest_better_performance = 1

let g:everforest_background = 'soft'

let g:everforest_transparent_background = 1 

colorscheme everforest

" Colemak bindings
noremap m h
noremap n j
noremap e k
noremap i l

nnoremap <silent> <C-m> :<C-U>TmuxNavigateLeft<cr>
nnoremap <silent> <C-n> :<C-U>TmuxNavigateDown<cr>
nnoremap <silent> <C-e> :<C-U>TmuxNavigateUp<cr>
nnoremap <silent> <C-i> :<C-U>TmuxNavigateRight<cr>

noremap k n
noremap K N
noremap u i
noremap l u
noremap f e
nnoremap cu ci
nnoremap vu vi
nnoremap du di

" Keybindings
nnoremap <leader>o :so<CR>
nnoremap <leader>e :Files<CR>
nnoremap <leader>fo :History<CR>
nnoremap <leader>fb :Buffers<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>

" Fixes the cursor issue 
if &term =~ 'ghostty'
  let &t_SI = "\<Esc>[2 q" " Bar in insert mode
  let &t_SR = "\<Esc>[3 q" " Underline in replace mode
  let &t_EI = "\<Esc>[2 q" " Block in normal mode
endif

if &term =~ 'tmux-256color'
  let &t_SI = "\<Esc>[2 q" " Bar in insert mode
  let &t_SR = "\<Esc>[3 q" " Underline in replace mode
  let &t_EI = "\<Esc>[2 q" " Block in normal mode
endif
