#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
 yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
 sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 main:26:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on            \
    focus_follows_mouse          autoshift             \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               on            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               alt             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    window_topmost               off

### Rules ###
if [ "$(defaults read -g AppleLocale)" = "ru_RU" ]; then
    safari_title="(Основные|Вкладки|Автозаполнение|Пароли|Поиск|Безопасность|Веб-сайты|Расширения|Дополнения)"
    yabai -m rule --add app="^Системные настройки$"                   manage=off
    yabai -m rule --add app="^Finder$" title="(Свойства|Настройки)"   manage=off
    yabai -m rule --add app="^Информация о системе$"                  manage=off
    yabai -m rule --add app="^Калькулятор$"                           manage=off
    yabai -m rule --add app="^Мониторинг системы$"                    manage=off
    yabai -m rule --add app="^Шрифты$"                                manage=off
    yabai -m rule --add app="^Утилита архивирования$"                 manage=off
    yabai -m rule --add app="^Цифровой колориметр$"                   manage=off
    yabai -m rule --add app="^Twitter$" title="(Медиа)"               manage=off
else
    safari_title="(General|Tabs|Autofill|Passwords|Search|Security|Privacy|Websites|Extensions|Advanced)"
    yabai -m rule --add app="^System Preferences$"                    manage=off
    yabai -m rule --add app="^System Information$"                    manage=off
    yabai -m rule --add app="^Finder$" title="(Info|Preferences)"     manage=off
    yabai -m rule --add app="^Calculator$"                            manage=off
    yabai -m rule --add app="^Activity Monitor$"                      manage=off
    yabai -m rule --add app="^Font Book$"                             manage=off
    yabai -m rule --add app="^Archive Utility$"                       manage=off
    yabai -m rule --add app="^Digital Colour Meter$"                  manage=off
    yabai -m rule --add app="^Twitter$" title="(Media)"               manage=off
fi

yabai -m rule --add label="App Store" app="^App Store$"           manage=off
yabai -m rule --add app="^Keka$"                                  manage=off
yabai -m rule --add app="^Vimari$"                                manage=off
yabai -m rule --add app="^Installer$"                             manage=off
yabai -m rule --add app="^VimR$" title="(Preferences)"            manage=off
yabai -m rule --add app="^Twitter$" title="(Медиа)"               manage=off
yabai -m rule --add app="^Spark$"                                 manage=off
yabai -m rule --add app="^Safari$" title="$safari_title"          manage=off

yabai -m rule --add app="^Arc$" subrole='AXSystemDialog' manage=off mouse_follows_focus=off
yabai -m rule --add app='^Arc$' title='^Space.*$' manage=off

# yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq '.[1].id // .[0].jd' )"

echo "yabai configuration loaded.."
borders active_color=0xff6c7d5e inactive_color=0xff3c454c style=square width=8.0 &
